# Generated by Django 3.2.4 on 2021-06-15 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='criados',
            new_name='criado',
        ),
        migrations.RenameField(
            model_name='cargo',
            old_name='modificados',
            new_name='modificado',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='criados',
            new_name='criado',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='modificados',
            new_name='modificado',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='criados',
            new_name='criado',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='modificados',
            new_name='modificado',
        ),
    ]
