# Generated by Django 3.2.4 on 2021-06-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_funcionario_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome_feature', models.CharField(max_length=100, verbose_name='Features')),
                ('descricao_feature', models.TextField(max_length=200, verbose_name='Descrição')),
                ('icone_feature', models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-laptop-phone', 'Lapto-Phone'), ('lni-cog', 'Engrenagem'), ('lni-leaf', 'Folha'), ('lni-layers', 'Camadas')], max_length=20, verbose_name='Icone')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
